Add html and css files with linting tools
waiyankyaw961999/Hello-World pull request #1
Opened 2023-04-26 04:40 UTC by waiyankyaw961999

- Add html file with a title 
- Add external css file

2023-04-26 05:32 UTC, Efiamotu-1 requested changes
Hi @waiyankyaw961999 , 

![](https://camo.githubusercontent.com/9394efa3662ade294180d682ebade56334efde7f9b0ffaf2da4786d70e86ee0c/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e6769663f6369643d65636630356534376b357561706470746730306e69646277337161787838697167737573676173776369326333756831267269643d67697068792e6769662663743d67)

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 05:32 UTC, Efiamotu-1 commented on README.md
> +<a name="readme-top"></a>
- [ ] A professional readme is equally very important as you go on through your lifestime as a micronaut, as in subsequent projects your project wont be reviewed unless your read me is very professional so i would suggest that once again you go through this [microverse readme template](https://github.com/microverseinc/readme-template) and you add every single section, the only optional section is the `faq` section. :+1: 
- [ ] Take note that for your readme, you are not required to use the microverse logo optionally you can put your logo :+1: 
- [ ] You are also required to remove all the words in each section which tells you how to customise a section, some of them start with `describe` :+1: 
- [ ] It is also impoortant that your readme doesn't contain broken links one important place is in your MIT license, you are expected to link the `MIT.md` or `LICENSE.md` file in your repo to the license section of your readme :+1:

2023-04-26 05:32 UTC, Efiamotu-1 commented on index.html
- [ ] It is also important to use good PR title and summary when making a pull request attached below is an image of how your pr title and summary for this project should look like please make sure to make the correct changes before resubmitting for a new pull request. :+1: 
- [ ] Make sure to also name your branches descriptively tailored to the changes you would be making for example `add-homepage`, `mobile-menu-feature` etc
![good-pr](https://user-images.githubusercontent.com/89055502/234389170-2ece21cc-1ad3-46e1-8e31-cb39f5f8304d.png)

2023-04-26 11:52 UTC, waiyankyaw961999 commented on README.md
> +<a name="readme-top"></a>
@Efiamotu-1  I do not get for the first thing you mentioned. I only dropped the sections that are not related to the project. As this project is just html and css, I did not include Getting Started Section. In the original README.md, it tells that I can remove the section that doesn't apply.  For the prerequisites section in the original README.md, there is a database and server information.

2023-04-26 11:56 UTC, waiyankyaw961999 commented on README.md
> +<a name="readme-top"></a>
For the third point, I did not include the sentence starts with the word - describe. According to your comment, what words should I remove specifically from the README.md. Please tell me.

2023-04-26 17:23 UTC, Efiamotu-1 commented on README.md
> +<a name="readme-top"></a>
@waiyankyaw961999 your readme actually needs the getting started section, this is the section where you add information detailing how users and recruiters can clone and make use of your repository. the getting started actually does apply to your project so please kindly add it :+1: 
- I mentioned the `describe` word just so if you planned on using the microverse template which has information on how to customise each section you remember to remove them below is an example of the describe word in the template. 
![des](https://user-images.githubusercontent.com/89055502/234653901-dd2bacc2-4426-4cd2-8549-7f0a2091e178.png)
Hope my explanations have been helpful

2023-04-27 07:22 UTC, wayungi approved these changes
Hi @waiyankyaw961999 , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] All linter checks passing ✔️ 
- [ ] Good commit messages ✔
- [ ]  Correct GitHub flow ✔️ 
- [ ] Descriptive PR body ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 07:22 UTC, wayungi commented on README.md
> + <img src="murple_logo.png" alt="logo" width="140"  height="auto" />
![logo](https://user-images.githubusercontent.com/99656687/234783802-4001c7ef-9b28-4cd5-a5f3-60771ca427f4.png)
- [ OPTIONAL]  This Microvers logo should always be deleted from your `readme`, You can replace it with your own logo if you do wish but the gist is to always **delete the Microverse logo** 🤝

2023-04-27 07:22 UTC, wayungi commented on README.md
> +> This project is testing a github workflows and linting for html and css.
![png](https://user-images.githubusercontent.com/99656687/234786183-d07952aa-cddb-4a19-90dd-cc0d77627a94.png)

- [ OPTIONAL] All lines beginning with a `>` deliminate a comment and should be deleted upon editing this document. I suggest that when you choose to edit and keep these lines please always remember to **delete** the `>` at the start

2023-04-27 07:22 UTC, wayungi commented on README.md
> +> No live demo
![demo](https://user-images.githubusercontent.com/99656687/234786424-ebe73f3b-9ff8-467b-85c4-7ba92c2ccfb4.png)
- [ ] Whenever your project is not deployed, kindly always delete this section 👍🏾

2023-04-27 07:22 UTC, wayungi commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
![start](https://user-images.githubusercontent.com/99656687/234787120-397bc075-fdbb-4ace-b911-73a9364d4743.png)
- [ OPTIONAL] You have omitted too much in this section. the only sections you could have safely omitted in this particular case are the **tests** since your project does not have tests and probably **deployment**. The rest of the sections should be edited and maintained 👍🏾

2023-04-27 07:22 UTC, wayungi commented on README.md
> +> No future features will be added.
![future](https://user-images.githubusercontent.com/99656687/234788282-495191bb-578c-4306-b335-bc81114c3335.png)

- [ OPTIONAL] Kindly note that this section is mandatory and should always be filled in. There is always room for improvement in any project. This is where you can outline those ideas. 😄

2023-04-27 07:36 UTC, waiyankyaw961999 commented on README.md
> +> No future features will be added.
thank you for your suggestion.

2023-04-27 07:37 UTC, merged